Repository ssl-hep/ServiceX_frontend, pull requests merged in 2024-09, with the labels that each got.

#455 Examples for xAOD
  .vscode/settings.json
  docs/examples.rst
  examples/func_adl_xAOD_simple.py
  examples/func_adl_xAOD_typed.py
  pyproject.toml
Labels: enhancement

#458 Fix minio handling of buckets in rare cases
  servicex/minio_adapter.py
Labels: bug

#472 Quick Proofread
  docs/command_line.rst
  docs/connect_servicex.rst
  docs/contribute.rst
  docs/index.rst
  docs/query_types.rst
  docs/transform_request.rst
Labels: documentation, enhancement

#478 Update the download progress bar (both unsigned and dowload) when initial transform request doesn't return all files
  servicex/query_core.py
Labels: verify
